[theme]

base="dark"

textColor = "#ffffff"
primaryColor = "#fffc9e"
backgroundColor = "#2a2a2e"
secondaryBackgroundColor = "#1e1e21"

showWidgetBorder = true
borderColor = "#3c3c42"

font = "Inter:https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
baseFontWeight = 400
baseFontSize = 14

headingFont = "Inter:https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
headingFontWeights = [600, 600, 600, 200, 600, 200]
headingFontSizes = ["3rem", "1.5rem", "1.25rem", "1rem", "0.8rem", "0.8rem"]